### Networks
networks:
  default:
    driver: bridge
  socket_proxy:
    name: socket_proxy
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.91.0/24
  t2_proxy:
    name: t2_proxy
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.90.0/24

### Secrets
secrets:
  cf_dns_api_token:
    file: $SHD_DIR_SECRETS/cf_dns_api_token
  authelia_jwt_secret:
    file: $SHD_DIR_SECRETS/authelia_jwt_secret
  authelia_session_secret:
    file: $SHD_DIR_SECRETS/authelia_session_secret
  authelia_storage_encryption_key:
    file: $SHD_DIR_SECRETS/authelia_storage_encryption_key

include:
  - compose/$SHD_HOST.yml