services:
  # Dynamic DNS Updater
  appserver-ddns-updater:
    image: qmcgaw/ddns-updater
    container_name: appserver-ddns-updater
    security_opt:
      - no-new-privileges:true
    restart: unless-stopped
    networks:
      - t2_proxy
    expose:
      - 8000
    volumes:
      - $SHD_DIR_APPDATA/$SHD_HOST/ddns-updater:/updater/data # Owned by UID 1000
    environment:
      TZ: $TZ
      PUID: $PUID
      PGID: $PGID
      PERIOD: 12h
      UPDATE_COOLDOWN_PERIOD: 5m
      PUBLICIP_DNS_TIMEOUT: 3s
      HTTP_TIMEOUT: 10s
      # Web UI
      LISTENING_PORT: 8000
      # Backup
      BACKUP_PERIOD: 96h # 0 to disable
      BACKUP_DIRECTORY: /updater/data/backups
      # Other
      LOG_LEVEL: info
#      SHOUTRRR_ADDRESSES: $DISCORD_SHOUTRRR_ADDRESS
    labels:
      - "traefik.enable=true"
      # HTTP Routers
      - "traefik.http.routers.ddns-updater-rtr.entrypoints=websecure"
      - "traefik.http.routers.ddns-updater-rtr.rule=Host(`ddns-updater.${DOMAINNAME}`)"
      # Middlewares
      - "traefik.http.routers.ddns-updater-rtr.middlewares=chain-authelia@file"
      # HTTP Services
      - "traefik.http.routers.ddns-updater-rtr.service=ddns-updater-svc"
      - "traefik.http.services.ddns-updater-svc.loadbalancer.server.port=8000"
      - "traefik.docker.network=t2_proxy"