services:
  appserver-mosquitto:
    container_name: appserver-mosquitto
    image: eclipse-mosquitto:$MOSQUITTO_VERSION
    security_opt:
      - no-new-privileges:true
    restart: unless-stopped
    networks:
      - t2_proxy
    environment:
      - TZ=$TZ
    volumes:
      - "$DOCKERDIR/appdata/$SHD_HOST/mosquitto/config:/mosquitto/config"
      - "$DOCKERDIR/appdata/$SHD_HOST/mosquitto/data:/mosquitto/data"
      - "$DOCKERDIR/appdata/$SHD_HOST/mosquitto/log:/mosquitto/log"
    ports:
      - 1883:1883