version: "3.9"

services:
  zwave-js-ui:
    container_name: zwavejsui
    image: zwavejs/zwave-js-ui:$ZWAVE_JS_UI_VERSION
    security_opt:
      - no-new-privileges:true
    restart: unless-stopped
    networks:
      - t2_proxy
    volumes:
      - $DOCKERDIR/appdata/$SHD_HOST/zwave-js-ui:/usr/src/app/store
    expose:
      - 8091
      - 3001
    ports:
      - "8091:8091"
      - "3001:3001"
    devices:
      - ${ZWAVE_JS_UI_DEVICE_PATH}:/dev/zwave
    environment:
      - SESSION_SECRET=${ZWAVE_JS_UI_SESSION_SECRET}
      - ZWAVEJS_EXTERNAL_CONFIG=/usr/src/app/store/.config-db
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    labels:
      - "traefik.enable=true"
      # HTTP Routers
      - "traefik.http.routers.zwave-js-ui-rtr.entrypoints=websecure"
      - "traefik.http.routers.zwave-js-ui-rtr.rule=Host(`zwave-js-ui.${DOMAINNAME}`)"
      # Middlewares
      - "traefik.http.routers.zwave-js-ui-rtr.middlewares=chain-authelia@file"
      # HTTP Services
      - "traefik.http.routers.zwave-js-ui-rtr.service=zwave-js-ui-svc"
      - "traefik.http.services.zwave-js-ui-svc.loadbalancer.server.port=8091"
      - "traefik.docker.network=t2_proxy"
    depends_on:
      mosquitto:
        condition: service_started