version: "3"

services:
  shd-eufy-security:
    container_name: shd-eufy-security
    restart: unless-stopped
    image: bropat/eufy-security-ws:0.9.1
    volumes:
      - ${DATADIR}/eufy-security
      - /etc/localtime:/etc/localtime:ro
    ports:
      - '3000:3000'
    environment:
      - USERNAME=${EUFY_SECURITY_USERNAME}
      - PASSWORD=${EUFY_SECURITY_PASSWORD}
      - COUNTRY=${EUFY_SECURITY_COUNTRY}
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
