version: "3"

services:
  homeassistant:
    container_name: shd-homeassistant
    restart: unless-stopped
    image: homeassistant/home-assistant:2022.5
    volumes:
      - ${DATADIR}/homeassistant/config:/config
      - /etc/localtime:/etc/localtime:ro
      - /dev/serial/by-id/:/dev/serial/by-id/
#    network_mode: host
    privileged: true
    ports:
      - 8123:8123
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    depends_on:
      shd-mosquitto:
        condition: service_started


