version: "3"

services:
  shd-homeassistant:
    container_name: shd-homeassistant
    restart: unless-stopped
    image: homeassistant/home-assistant:2022.10
    volumes:
      - ${DATADIR}/homeassistant/config:/config
      - /etc/localtime:/etc/localtime:ro
      - /dev/serial/by-id/:/dev/serial/by-id/
      - /run/dbus:/run/dbus:ro
    network_mode: host
    privileged: true
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    depends_on:
      shd-mosquitto:
        condition: service_started



