version: "3"

services:
  shd-zigbee2mqtt:
    container_name: shd-zigbee2mqtt
    image: koenkk/zigbee2mqtt
    depends_on:
      mosquitto:
        condition: service_started
    restart: unless-stopped
    volumes:
      - ${DATADIR}/zigbee2mqtt/data:/app/data
      - /run/udev:/run/udev:ro
    devices:
      - /dev/ttyACM0:/dev/zigbee
    environment:
      - TZ=${TZ}

  shd-zigbee2mqttAssistant:
    container_name: shd-zigbee2mqttAssistant
    image: carldebilly/zigbee2mqttassistant
    restart: unless-stopped
    depends_on:
      zigbee2mqtt:
        condition: service_started
    environment:
      - Z2MA_SETTINGS__MQTTSERVER=mosquitto
      - TZ=${TZ}
    ports:
      - 8880:80