version: "3"

services:
  shd-zwavejs2mqtt:
    container_name: shd_zwavejs2mqtt
    restart: unless-stopped
    image: zwavejs/zwavejs2mqtt:latest
    volumes:
      - ${DATADIR}/zwavejs2mqtt:/usr/src/app/store
    ports:
      - '8091:8091'
      - '3000:3000'
      - '3001:3001'
    devices:
      - ${ZWAVEJS2MQTT_DEVICE_PATH}:/dev/zwave
    environment:
      - SESSION_SECRET=${ZWAVEJS2MQTT_SESSION_SECRET}
      - ZWAVEJS_EXTERNAL_CONFIG=/usr/src/app/store/.config-db
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    depends_on:
      shd-mosquitto:
        condition: service_started