version: "3"

services:
  shd-zerotier:
    container_name: shd-zerotier
    restart: unless-stopped
    image: zyclonite/zerotier
    volumes:
      - ${DATADIR}/zerotier/config:/var/lib/zerotier-one
      - /etc/localtime:/etc/localtime:ro
    network_mode: "host"
    devices:
      - /dev/net/tun
    cap_add:
      - NET_ADMIN
      - SYS_ADMIN
    privileged: true
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
